name: gardenlinux
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [ amd64, arm64 ]
        platform: [ kvm, metal, gcp, aws, azure, ali, openstack, vmware ]
        modifier: [ "", "-dev" ]
    steps:
      - uses: actions/checkout@v2
      - run: wget https://deb.debian.org/debian/pool/main/q/qemu/qemu-user-static_6.2+dfsg-1_amd64.deb && sudo dpkg -i qemu-user-static_6.2+dfsg-1_amd64.deb
      #- run: make ARCH=${{ matrix.architecture }} BUILD_OPTS=--skip-tests ${{ matrix.platform }}${{ matrix.modifier }}
      - run: mkdir .build && echo hello > .build/${{ matrix.architecture }}-${{ matrix.platform }}${{ matrix.modifier }}.txt
      - uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.architecture }}-${{ matrix.platform }}${{ matrix.modifier }}
          path: .build
  release:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [ amd64, arm64 ]
        platform: [ kvm, metal, gcp, aws, azure, ali, openstack, vmware ]
        modifier: [ "", "-dev" ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build-${{ matrix.platform }}${{ matrix.modifier }}
          path: .build
      - run: find .build -type f | .github/workflows/upload_release.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} "gardenlinux_$(bin/garden-version)"
