name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [ amd64 ]
        target: [ openstack ]
        modifier: [ "-dev" ]
    steps:
      - uses: actions/checkout@v2
      - run: |
          version=$(curl -s -f https://deb.debian.org/debian/pool/main/q/qemu/ | grep -oP '(?<=href="qemu-user-static_).*?(?=_amd64.deb")' | sort | tail -n 1)
          wget https://deb.debian.org/debian/pool/main/q/qemu/qemu-user-static_${version}_amd64.deb
          sudo dpkg -i qemu-user-static_${version}_amd64.deb
      - run: make BUILD_OPTS=--lessram ARCH=${{ matrix.architecture }} ${{ matrix.target }}${{ matrix.modifier }}
